### ISSUE TITLE
期待！！！

### ISSUE THREAD

**Issue by leesings** [adonais/skylark#1]
偶然发现这个很好用的编辑器，够轻量，启动很快，可以自动保存，代码高亮也很优秀。
美中不足是不支持触摸板水平滚动，还有右下角那个读写和大写没太看懂，期待能自定义快捷键！

**Comment by adonais** [comment]
触摸板水平滚动问题已修复.
"读写"按钮指示文件是可读可写状态.
"大写"按钮提示键盘输入是大写字母.

**Comment by leesings** [comment]
感谢，谢谢修复，期待！

**Comment by leesings** [comment]
发现一直向右水平滚动，即使文本到了右边界，也不会停下来。

**Comment by adonais** [comment]
> 
> 
> 发现一直向右水平滚动，即使文本到了右边界，也不会停下来。

已修复
