### ISSUE TITLE
支持类似notepad++的搜索结果展示窗口

### ISSUE THREAD

**Issue by Wood-Xia** [adonais/skylark#10]
## 当前问题
当前搜索结果仅仅在当前文件中高亮，无法对某个文件或某个目录下的文件搜索结果进行汇总展示

## 建议
支持类似Notepad++的搜索结果展示窗口，方便对类似日志文档等进行分析
![image](https://user-images.githubusercontent.com/4701967/176361986-5bfe5e3f-11a4-4b0c-b55c-9b3844000de7.png)

**Comment by Wood-Xia** [comment]
When could release this feature? Any plan?

**Comment by Wood-Xia** [comment]
@adonais 
Any update? Or already available?
I could not find in recent release.

**Comment by adonais** [comment]
> 

![sshot-3](https://user-images.githubusercontent.com/11960628/188909972-53a083e4-aeac-461e-8e6a-5b1e418892aa.jpg)
新版本不是已经有了吗?  不过它只提供当前文件的汇总展示. 可同时展示多个文件在不同标签.

**Comment by Wood-Xia** [comment]
@adonais 
我下载了最新release的版本，但是我看到不到你上面的搜索结果窗口呀。
可以截图展示一下操作步骤吗？谢谢！

下图是我的相关版本和操作截图

![image](https://user-images.githubusercontent.com/4701967/191211786-f0105a4c-5fdc-46ec-a890-d3f7e86e59fc.png)

![image](https://user-images.githubusercontent.com/4701967/191211937-aa4fc83c-c6cf-429f-86ed-e3e83fac2654.png)

![image](https://user-images.githubusercontent.com/4701967/191212058-84719f88-766f-4e19-b2d3-37b1a4cd3436.png)

![image](https://user-images.githubusercontent.com/4701967/191212393-45e36c13-1d19-4dce-97fa-06efc9843d89.png)

**Comment by adonais** [comment]
显示详情,然后双击列表里面的文件
