### ISSUE TITLE
为 “自动复制超链接” 添加功能开关

### ISSUE THREAD

**Issue by Bush2021** [adonais/skylark#119]
左键单击超链接会自动触发 `on_hyper_click` 函数中的 `on_edit_push_clipboard`，请问能否关闭这个功能？

因为有时候复制了一段链接内容想要编辑超链接时，自动复制会导致剪切板内容被替换掉，从而无法正确粘贴我想要的内容。

**Comment by adonais** [comment]
有道理!

**Comment by Bush2021** [comment]
主要是我用的其它编辑器，例如 VSCode 没有这样的逻辑，所以不太习惯想关掉；如果不方便加个开关那就这样吧，感谢你的回复和贡献！
