### ISSUE TITLE
双屏下，主副屏分辨率不一致，菜单显示异常

### ISSUE THREAD

**Issue by ZxcSoft** [adonais/skylark#13]
从主屏拖动到副屏时， 显示异常了

主副屏分辨率不一致

![image](https://user-images.githubusercontent.com/5788555/183851069-d31067b4-91fa-4148-893a-79bf0f9b2fcf.png)
![image](https://user-images.githubusercontent.com/5788555/183851268-6bf4235e-0f61-4389-ba17-c3265360b1fc.png)
![image](https://user-images.githubusercontent.com/5788555/183851331-d1e84af2-a4f7-436b-8521-ba41d46fa0b4.png)

**Comment by adonais** [comment]
默认主题或暗黑主题是否也是这种情况? 菜单栏是自己隐藏的还是被遮挡了?

**Comment by ZxcSoft** [comment]
默认主题下出现的。 
感觉是渲染的问题。刚开始拖动到分屏时渲染是正常的
![image](https://user-images.githubusercontent.com/5788555/184823786-9fd9f724-6b09-4fa1-aa26-cd55fe08707d.png)

大部分内容拖动到分屏时，就会出现， 这时看出来整个工具重新渲染字体大小了
![image](https://user-images.githubusercontent.com/5788555/184824048-6fe3183a-0108-45d2-b52d-8f368538dbc7.png)

**Comment by ZxcSoft** [comment]
全屏的时候还渲染的有问题
![image](https://user-images.githubusercontent.com/5788555/184824466-11b2d2e4-7442-4a25-81fe-5d49469e52ff.png)

**Comment by adonais** [comment]
抱歉, 我这里没法重现

**Comment by ZxcSoft** [comment]
可以关闭了.  2.0.10版本好像解决了
