### ISSUE TITLE
工具栏的图标可否加一套大一点的

### ISSUE THREAD

**Issue by gooker** [adonais/skylark#14]
如题,4k分辨率太小了.
![image](https://user-images.githubusercontent.com/5688076/186390064-66513fac-22bf-46ca-a47c-d2594f743abe.png)

**Comment by adonais** [comment]
工具栏太大会占用客户区空间, 工具栏会根据dpi调整大小

**Comment by gooker** [comment]
### 我没有特殊设置字体大小,这个是对比,按钮还没有字体大,不熟练的情况下,很难点到按钮

![image](https://user-images.githubusercontent.com/5688076/189779642-4684ae19-b504-4677-8f6a-77cecc2d370f.png)

**Comment by adonais** [comment]
看来4k下24x24的图标比较合适, 或许下个大版本会添加进去.目前2.x版本不会再添加新特性.

**Comment by gooker** [comment]
> 看来4k下24x24的图标比较合适, 或许下个大版本会添加进去.目前2.x版本不会再添加新特性.

大版本有计划什么时候吗
