### ISSUE TITLE
空白字符显示能否更小一点、透明度更低一点 或者放在主题里允许自定义？

### ISSUE THREAD

**Issue by 0x152a** [adonais/skylark#17]
当前效果
![image](https://user-images.githubusercontent.com/62497850/191390914-6a28c6e1-32d8-4cd3-b5bf-da2b3513c75e.png)
不太好区分`·`字符和空格
![image](https://user-images.githubusercontent.com/62497850/191391262-64d51dfb-ebb7-4e84-82c2-2c9a4f414208.png)

Notepad3的效果，感觉更清晰一点
![image](https://user-images.githubusercontent.com/62497850/191390679-cbe80a43-a540-41cd-b287-a7abd9bef987.png)
![image](https://user-images.githubusercontent.com/62497850/191391432-75a4d71a-adc6-4e4c-bc9f-a625d9f50829.png)

**Comment by adonais** [comment]
skylark.conf文件可设置空白字符大小, 默认white_space_size=3, 
下个版本会修复透明度的问题.
