### ISSUE TITLE
感觉有内存泄漏情况

### ISSUE THREAD

**Issue by leesings** [adonais/skylark#2]
![image](https://user-images.githubusercontent.com/43227866/130482312-c7695a10-cce1-4c66-910e-7d2b45d73244.png)

打开软件一段时间后，桌面窗口管理器内存占用持续上升，且不停止，直到爆满。
不打开此软件没有这个现象，猜测与这有关。

**Comment by adonais** [comment]
你这个DWM已经占用内存上GB了, 我不认为是受skylark影响.
skylark在标签或窗口关闭时, 会释放所有已知分配的内存.

**Comment by leesings** [comment]
现在没有出现这个问题了，感觉正常了
