### ISSUE TITLE
【Bug】版本检测一直显示正在检测

### ISSUE THREAD

**Issue by istek** [adonais/skylark#21]
版本号：2.0
编译日期：2022-09-12
OS： Win10 22H2

![image](https://user-images.githubusercontent.com/8424803/197096174-678c9568-d821-456a-b85c-82465107effd.png)

**Comment by adonais** [comment]
链接超时的时间是6秒. 可能是国内防火墙干扰造成了这种情况, 或许应该设置一个下载超时时间?
