### ISSUE TITLE
希望增加 Zh-tw 語言

### ISSUE THREAD

**Issue by KioChong** [adonais/skylark#25]
或者能否說明一下怎么把zh-cn 的dll.弄成zh-tw..thanks.

**Comment by adonais** [comment]
这个需要自行翻译
1, 把locales\src\zh-cn.rc复制一份, 命名为zh-tw.rc
2, 用skylark打开zh-tw.rc, 使用"简体转繁体功能"把zh-tw.rc转为繁体.
3, 编辑zh-tw.rc, 主要是把简体系的it术语转换为繁体系的IT术语, 比如"硬盤"改成"硬碟"之类的称呼.
4, 你可以使用git pull-request向我发送修改后的源码. 如果不会这一步, 直接把zh-tw.rc压缩后放在留言里的附件也可以.

**Comment by KioChong** [comment]
[zh-tw.zip](https://github.com/adonais/skylark/files/9918092/zh-tw.zip)

**Comment by adonais** [comment]
原始的zh-cn.rc文件不是这种html格式, 如果你不会使用git clone得到zh-cn.rc,可以使用
https://raw.githubusercontent.com/adonais/skylark/main/locales/src/zh-cn.rc
链接得到. 并且也没有处理简繁it术语的差别.
