### ISSUE TITLE
3.0 标签问题

### ISSUE THREAD

**Issue by gooker** [adonais/skylark#27]
3.0基本上挺不错,之前2.0偶尔用用,现在我可以替代emeditor文本编辑,写代码我用sublime和vscode,至少这俩配色以及c++的高亮好不少,但是也能看出来skylark有不少方便的地方.

发现几个问题 
1.标签点x关闭有时候关闭不掉,最后一个比较明显,右键关闭标签可以;
2.关闭标签明显有闪烁问题,这个比较严重;
3.符号连接窗口 字体比页面字体大不少,看起来不合适.

**Comment by adonais** [comment]
你说的符号连接窗口字体比页面字体大不少, 什么意思? 俩边字体不都是一样大小吗

**Comment by gooker** [comment]
就是显示函数名的那个右边栏，字体大，我是4k dpi可能是200%



---原始邮件---
发件人: "hua ***@***.***&gt;
发送时间: 2022年11月19日(周六) 上午8:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [adonais/skylark] 3.0 标签问题 (Issue #27)




 
你说的符号连接窗口字体比页面字体大不少, 什么意思? 俩边字体不都是一样大小吗

**Comment by adonais** [comment]
> 就是显示函数名的那个右边栏，字体大，我是4k dpi可能是200%
> […](#)
> ---原始邮件--- 发件人: "hua ***@***.***&gt; 发送时间: 2022年11月19日(周六) 上午8:32 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [adonais/skylark] 3.0 标签问题 (Issue #27) 你说的符号连接窗口字体比页面字体大不少, 什么意思? 俩边字体不都是一样大小吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

抱歉, gmail要验证的那个手机号已遗失, 我在页面上更新了新的email

**Comment by gooker** [comment]
> 

这个是github有更新直接发我邮箱 我在邮箱直接回复的,不是在网页上回复的,不是我要给你发邮箱
