### ISSUE TITLE
若干关于3.0版的问题

### ISSUE THREAD

**Issue by TaicEart** [adonais/skylark#28]
- [ ] 自己之前已经安装了 SumatraPDF，可以替换 plugins 里的吗。或允许指定 Skylark 用我安装的 SumatraPDF 路径？

- [ ] 我使用的对比软件是开源的 [WinMerge](https://winmerge.org/)，是否能自定义对比软件，或针对 WinMerge 作一些兼容？

- [ ] Skylark 不默认支持其自身配置里的 .snippets 文件语法高亮（是 Perl 高亮吗）

**Comment by adonais** [comment]
你可以使用官方版本的SumatraPDF替换, 但因为官方版本少了一些通信接口, 一些东西会不一样, 自己试试就知道了. 插件只会搜索plugin目录, 放在别的目录无效.
发送到bc菜单应该也可以调用winmerge, 当标签是16进制时, 调用bc直接使用16进制比较, winmerge的16进制比较下个版本加进去.
snippets 语法不是Perl, 不支持, 本来就有代码片段编辑器, .snippets文件是否高亮不重要, 没必要做的那么全.
