### ISSUE TITLE
开关标签 滚动条和菜单栏还是刷新,链接栏效果如图

### ISSUE THREAD

**Issue by gooker** [adonais/skylark#29]
开关标签还是挺明显,菜单貌似都在刷新.
还有第二个图的主题是参考 vscode改的,不过貌似函数名 无效,不确定怎么配置, 另外 修改完主题 备份styletheme.conf就行了吧?

![GIF](https://user-images.githubusercontent.com/5688076/203224747-20d53934-4112-4ee0-8541-ed8d0842527d.gif)
![2022-11-22_124519](https://user-images.githubusercontent.com/5688076/203224846-b4ccb4f7-b02a-4908-8379-65334b3e05c1.jpg)

**Comment by adonais** [comment]
标签切换时, 涉及到一系列的窗口刷新, 只能尽可能的缓和, 不会完全没有, 不影响日常使用的眼部不适就行了. 
右侧函数名的提取是靠正则表达式, 因为c++函数与类声明的复杂性, 不能做到完全准确. 如果你有更合适的正则, 可以自行修改
conf\script-opts\user_cpp.lua文件里面的get_reqular(). 修改错误了会引起编辑器不能启动. 删除user_cpp.lua文件, 然后继续测试.
styletheme*.conf是全局主题文件, 如果你通过菜单修改的配色方案, 备份它们就可以了. 
针对各文件类型, 你可以通过conf\script-opts\文件夹下的lua脚本get_styles函数, 可以精细到每一类关键字配色.
右侧边栏的字体是跟随标准菜单字体进行缩放, 并不是跟随编辑区的字体. 因为有人可能会把编辑区字体设置很大, 那么侧边栏的字体到底要不要跟随?  这个字体设置或许可以写在主题文件里, 我需要先考虑下主题风格菜单的整体设计.

**Comment by gooker** [comment]
> 标签切换时, 涉及到一系列的窗口刷新, 只能尽可能的缓和, 不会完全没有, 不影响日常使用的眼部不适就行了. 右侧函数名的提取是靠正则表达式, 因为c++函数与类声明的复杂性, 不能做到完全准确. 如果你有更合适的正则, 可以自行修改 conf\script-opts\user_cpp.lua文件里面的get_reqular(). 修改错误了会引起编辑器不能启动. 删除user_cpp.lua文件, 然后继续测试. styletheme*.conf是全局主题文件, 如果你通过菜单修改的配色方案, 备份它们就可以了. 针对各文件类型, 你可以通过conf\script-opts\文件夹下的lua脚本get_styles函数, 可以精细到每一类关键字配色. 右侧边栏的字体是跟随标准菜单字体进行缩放, 并不是跟随编辑区的字体. 因为有人可能会把编辑区字体设置很大, 那么侧边栏的字体到底要不要跟随? 这个字体设置或许可以写在主题文件里, 我需要先考虑下主题风格菜单的整体设计.

右侧的那些函数名 既然能识别到,  那代码里面高亮函数名应该也可以吧?我没看到效果,不知道具体配置哪个字段,配置好了 我看改个名就成一个主题, 到时候我发出来

**Comment by gooker** [comment]
请问一下  function/method 对应 cpp里面哪些? 自己能改user_cpp.lua匹配吗 ,设置了在cpp内没看到效果
<img width="653" alt="1670132789254" src="https://user-images.githubusercontent.com/5688076/205476582-32d7783b-4b7b-40cc-a649-9611c0921f0a.png">

**Comment by adonais** [comment]
我说过了, user_***.lua可以更改, 但最好知道自己在改什么? 如果语法出错了会导致编辑器不能再启动, 这时候你需要删除这个文件.
你标记的地方指的是c/c++内置函数的高亮颜色, 例如"strlen, strstr"这些, 如果你需要增加一些函数的高亮显示, 对应修改user_cpp.lua文件的get_keywords()函数, keywords1_set变量.
如果你需要增加一些函数的自动补全, 把它们追加到get_autocomplete(), autocomplete_set变量里.
如果你需要增加某些函数的自动提示, 把它们追加到get_calltip(), calltip_add变量里.

**Comment by gooker** [comment]
我看了，关键字/提示都没问题，我的意思是把所有页面里面的函数，或者我自己的正则表达式包含的高亮成一种颜色。 本来以为是设置里面的function/method，貌似不是



---原始邮件---
发件人: "hua ***@***.***&gt;
发送时间: 2022年12月4日(周日) 晚上7:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [adonais/skylark] 开关标签 滚动条和菜单栏还是刷新,链接栏效果如图 (Issue #29)




 
我说过了, user_***.lua可以更改, 但最好知道自己在改什么? 如果语法出错了会导致编辑器不能再启动, 这时候你需要删除这个文件.
 你标记的地方指的是c/c++内置函数的高亮颜色, 例如"strlen, strstr"这些, 如果你需要增加一些函数的高亮显示, 对应修改user_cpp.lua文件的get_keywords()函数, keywords1_set变量.
 如果你需要增加一些函数的自动补全, 把它们追加到get_autocomplete(), autocomplete_set变量里.
 如果你需要增加某些函数的自动提示, 把它们追加到get_calltip(), calltip_add变量里.
