### ISSUE TITLE
要是有个文件对比功能就完美了

### ISSUE THREAD

**Issue by NorthStar1226** [adonais/skylark#31]
类似于Notepad++的compare插件那种就足以

**Comment by gooker** [comment]
支持啊 选两个页面 可以设置调用bcompare

**Comment by NorthStar1226** [comment]
电脑没有正版beyondcompare哇，而且单个文件对比，内置的比较方便，Android Stuido里面也有个这样的功能

**Comment by adonais** [comment]
> 电脑没有正版beyondcompare哇，而且单个文件对比，内置的比较方便，Android Stuido里面也有个这样的功能
专业的对比软件功能更强大, 内置的对比功能完全不符合我的要求.
