### ISSUE TITLE
有没有编译环境搭建的教程

### ISSUE THREAD

**Issue by gooker** [adonais/skylark#34]
Win下没有弄过编译,vscode,或者qt可以吗

**Comment by adonais** [comment]
电脑需要安装Visual Studio编译器, 2019或2022.
通过开始菜单打开Visual Studio编译器的命令行环境(x64 Native Tools Command Prompt之类...).
切换到源代码目录, 执行nmake clean && nmake

**Comment by gooker** [comment]
> 电脑需要安装Visual Studio编译器, 2019或2022. 通过开始菜单打开Visual Studio编译器的命令行环境(x64 Native Tools Command Prompt之类...). 切换到源代码目录, 执行nmake clean && nmake

ok
