### ISSUE TITLE
如何手动指定字符集再载入文件

### ISSUE THREAD

**Issue by hingbong** [adonais/skylark#35]
对于自动检测字符集不准确的时候，需要手动指定字符集再载入文件，当前好像没找到这个功能
谢谢

**Comment by adonais** [comment]
一般来说, 懂得手动指定字符集的人肯定对字符集这东西有所了解, 他们完全可以事先把文件保存为符合国际标准的字符集.
并且我对skylar的自动检测率比较满意, 至少比UE要好,你说的功能不在开发计划中.
