### ISSUE TITLE
Auto delete illegal  characters in filename while saving file 建议：保存文件时自动删除文件名中的非法字符

### ISSUE THREAD

**Issue by criime** [adonais/skylark#36]
When I copy a text row ,  Save to file, paste the text, save fail because the text contain invisible NEW-LINE which is hard to find.

当复制一整行，另存为，粘贴文本，确定，报错了。因为文本包括了不可见的换行符。

It is recommended to automatically delete illegal characters and invisible characters, such as “: / \”  when saving files.

建议在保存文件时，自动删除非法字符、不可见字符，如 " : \ / ", 回车。

**Comment by adonais** [comment]
严格意义上讲, 行如果包含了换行符, 那么它就属于行的一部分.
至于帮助用户删除文件名非法字符, 这不属于一款编辑器该有的功能.
