### ISSUE TITLE
编辑html文件时，当弹出候选标签或属性时，按退格键清除当前输入，会导致程序闪退

### ISSUE THREAD

**Issue by jms4000** [adonais/skylark#37]
编辑html文件时，当弹出候选标签或属性时，按退格键清除当前输入，会导致程序闪退

**Comment by waloyn** [comment]
闪退很频繁，不仅是html文件，php js sql json python 等等都会闪退，有时候刚打一个字符上去就闪退了，有时候正准备保存的时候闪退。

**Comment by jms4000** [comment]
我这里其他语言的都很正常，只有html文件有，可能因为html文件弹出候选词时是在尖括号之间的，希望尽早修复，试了好多试图代替notepad++的，只有这个我感觉是最好的
