### ISSUE TITLE
软件无法打开，我该如何排查问题？

### ISSUE THREAD

**Issue by H-Tung** [adonais/skylark#38]
已经不记得之前干过什么了……
现在无论双击/Enter都无法在任务管理器观察到相关进程。尝试过删除整个软件目录，无效。
软件是下载的最新的 3.0.2

版本	Windows 10 专业版
版本号	22H2
安装日期	‎2022/‎9/‎2
操作系统内部版本	19045.2364
体验	Windows Feature Experience Pack 120.2212.4190.0

**Comment by adonais** [comment]
skylark进程不存在, 意味着没有启动, skylark是支持Windows 10 22h2的, 你可以看看是不是杀毒软件之类的问题.

**Comment by H-Tung** [comment]
> 杀毒软件之类的问题

应该不是，我的电脑里只有 Windows Defender和火绒，刚刚还去火绒里加了安全区，仍然照旧。

打开某些在先前版本添加关联的文件格式时仍然会弹出skylark的安全提醒，但是打开新版程序就是打不开，后来才在README里面发现建议新版要删除全部旧版、可能打不开的提醒，我一般只看下release的说明……

能否通过清理目录/注册表解决这一问题呢？还是只能重置系统了……

**Comment by adonais** [comment]
看到火绒有种不好的感觉, 卸载试试.
![sshot-3](https://user-images.githubusercontent.com/11960628/212526278-dee5c772-6277-4e18-90a8-46810339cb5b.png)

**Comment by H-Tung** [comment]
我是知道正常来说能运行的……在 Windows 自带的 Sandbox 里就是正常的，但是就是启动不了……

无所谓了，这系统也运行了快一年了，重置一次了事，反正多数应用都在 [ScoopInstaller/Scoop: A command-line installer for Windows.](https://github.com/ScoopInstaller/Scoop) ，也谢谢您的耐心回复~💖
