### ISSUE TITLE
建议：二维码图片建议使用动态大小和纯黑白

### ISSUE THREAD

**Issue by criime** [adonais/skylark#40]
二维码功能的建议：
1、图片大小根据文字内容的多少，自动尺寸，避免强制缩放导致图片模糊，降低识别成功率。
2、颜色建议纯黑白，也是为了提高识别成功率。
3、显示图片时，背景为30%透明灰色，突出图片。
4、显示图片时，按任意键关闭图片。
5、显示图片时，鼠标点击图片以外的区域，也可以关闭图片。
6、显示图片时，鼠标滚轮可以实现图片放大和缩小，每次修改黑点的边长px值，确保图片不模糊。
7、图片应该包括外侧白色边框，这是识别需要的。

**Comment by adonais** [comment]
二维码功能只是为了实现与其他设备简单共享, 并且二维码能保存文字的多少也是有限度的, 没必要太复杂.

**Comment by TaicEart** [comment]
颜色纯黑白，和图片包括外侧白色边框，按任意键或点击图片以外的区域关闭图片，这几个需求是需要的。（点击图片关闭图片，和我个人在其它软件上的习惯不同）
经测试如果转换过多文字，二维码会因为无反锯齿的取整缩小而走形。不过我还没这个需求。

**Comment by adonais** [comment]
响应任意键或任意点击需要对键盘鼠标使用全局钩子, 这涉及到一些敏感api, 可能导致一些杀毒软件的误判.
按ESC可以退出窗口.
