### ISSUE TITLE
3.0的标签风格问题

### ISSUE THREAD

**Issue by gooker** [adonais/skylark#41]
skylark用了挺长时间,用途是做一个简单的文本类型的编辑器,替代注入notepad.++.需求就是速度快.功能多.
但是目前影响我使用的就是标签的问题,一个是有一些闪烁的问题和不方便(小?),我想改成原生标签可能对我更合适.

下面的截图是我常用的几个编辑器的标签样式,仅供参考.
sublime和vscode,标签都非常好
emedit/scite 便签简单,但是从来没有使用上的困惑

**Comment by adonais** [comment]
使用原生风格可以减少很多代码, 但win32 tab控件的原生风格对多行标签的处理有问题.
skylark默认支持多行标签, 并且支持标签多选状态下的拖曳, 比较, 关闭, 以及某些编辑操作. 
你看到的标签轻微闪烁可能是绘制关闭按钮引起的, 所以我在新版本里可能会增加几种绘制关闭按钮的方式.
0, 跟随鼠标(也就是目前默认的方式), 1, 在每个标签上绘制, 2, 不绘制(适合鼠标中键关闭标签的用户)

**Comment by gooker** [comment]
> 使用原生风格可以减少很多代码, 但win32 tab控件的原生风格对多行标签的处理有问题. skylark默认支持多行标签, 并且支持标签多选状态下的拖曳, 比较, 关闭, 以及某些编辑操作. 你看到的标签轻微闪烁可能是绘制关闭按钮引起的, 所以我在新版本里可能会增加几种绘制关闭按钮的方式. 0, 跟随鼠标(也就是目前默认的方式), 1, 在每个标签上绘制, 2, 不绘制(适合鼠标中键关闭标签的用户)

对比了一下 关闭标签,整个页面闪,我录了对比个图片

![GIF](https://user-images.githubusercontent.com/5688076/215968832-8a98d1d6-5b33-42ef-842c-379756051da2.gif)

**Comment by gooker** [comment]
我改了标签颜色,现在关闭窗口不闪烁了,问题关闭
