### ISSUE TITLE
列选择模式下好卡

### ISSUE THREAD

**Issue by AoThen** [adonais/skylark#42]
列选择模式下好卡
![image](https://user-images.githubusercontent.com/32790381/216022085-8a5e4198-73de-435c-b42e-0a287acf604a.png)
版本：Release 20230117130733

**Comment by adonais** [comment]
无法重现, 你可能需要提供更多的细节

**Comment by AoThen** [comment]
在Win10环境下，Alt+鼠标左键，列选择模式下，明显可见的卡顿，直接用鼠标划选无卡顿问题

**Comment by AoThen** [comment]
最新版Release 20230214215518又没这个问题了,本机变化是没有外接显示器了,我怀疑是外接显示器导致的,晚点我再试试

**Comment by AoThen** [comment]
已在最新版未复现,看样子已解决
