### ISSUE TITLE
分享自用参考vscode dark的主题

### ISSUE THREAD

**Issue by gooker** [adonais/skylark#43]
![image](https://user-images.githubusercontent.com/5688076/216495874-9f109374-7969-46aa-8894-e682110f9be6.png)

下面文件解压缩后放到conf目录下面,菜单 选择主题方案 vsdark
[styletheme_vsdark.zip](https://github.com/adonais/skylark/files/10574966/styletheme_vsdark.zip)

里面设置的字体是 "YaHei Fira Icon Hybrid"   雅黑和fira组合
https://github.com/hanleylee/yahei-fira-icon-hybrid-font

**Comment by adonais** [comment]
非常棒的配色, 字体也看得很舒服.
我一直在考虑是否应该提供便携式字体功能, 使用户免去安装字体这一步.
但因为dwrite下的字体加载必须要c++实现, 与我源代码的c代码不符.

**Comment by gooker** [comment]
> 非常棒的配色, 字体也看得很舒服. 我一直在考虑是否应该提供便携式字体功能, 使用户免去安装字体这一步. 但因为dwrite下的字体加载必须要c++实现, 与我源代码的c代码不符.

涉及中文字体都不小,这个字体受众主要是用来写代码,还是比较小众,感觉没必要为了小众需求做
