### ISSUE TITLE
询问  - 支援超链接跳转，自动补全

### ISSUE THREAD

**Issue by ykz0608** [adonais/skylark#44]
想请问之后的版本是否会支援单击ctrl即可跳转超链接功能。
还有自动补全的功能目前是以enter为触发键，能否支援tab键触发？

![image](https://user-images.githubusercontent.com/55829277/216768027-597b3d7e-264a-43bf-a217-fee937c9b781.png)

**Comment by adonais** [comment]
不明白所谓的"跳转超链接功能"是什么
以tab键触发的是代码片段功能, 当补全字符串前面出现图标的时候, 按tab键触发代码片段, 按工具栏上的s图标可自定义代码片段.

**Comment by ykz0608** [comment]
了解

跳转超链接功能以vscode为例，就像下图一样，当打开的文本有超链接时，能通过ctrl+点击链接的方式直接用浏览器打开
![image](https://user-images.githubusercontent.com/55829277/216771129-5c521f66-5183-43b7-bbe1-628bb4e85388.png)
