### ISSUE TITLE
编辑txt后缀的文件，按tab键不正常

### ISSUE THREAD

**Issue by jms4000** [adonais/skylark#45]
1。当光标在数字前时按tab键，会在数字前加上 regular expression test! 数字后加上 , number = , none =  ...  原数字后的文本会转到下一行，再按tab则会转到下一行文字前面
2。当在别的位置按tab键时，会往前查找第一个空白符，并把之前的文字清除并插入tab空格，再按tab键继续前面的操作，如果遇到数字就会如上操作，如果遇到标点符号，后面继续按tab键就会正常；
3。如果选择多行再按tab键，则是最后一行按上面的情况操作；
4。总之是按tab键会影响光标的不正常位置移动，并且有时会清除或插入文字；
5。其他后缀或没有后缀的文件没发现有这种情况；

**Comment by adonais** [comment]
这是对代码片段正则表达式功能的一个测试, 如果引起了你的不便,
打开conf\snippets\text.snippets文件, 清空它.
如果你想删除conf\snippets\text.snippets文件, 
请同时删除conf\conf.d\snippets\text.snippets.

关于tab键有时会清除文字, 这是一个bug, 我会尽快修复.

**Comment by jms4000** [comment]
ok,谢谢
