### ISSUE TITLE
默认白色经典的配色似乎不太好（只是建议）

### ISSUE THREAD

**Issue by akkuman** [adonais/skylark#46]
![image](https://user-images.githubusercontent.com/7813511/218616817-bfd26e98-0121-4666-af0b-0b6ac682607e.png)
对比度似乎比较低，可能类似vs那种蓝白更好点（只是建议）

**Comment by adonais** [comment]
配色方案多达几百种, 默认的配色并不能兼顾到所有, 这个需要时间去积累, 我也希望网友们有更好的配色方案发给我😄
