### ISSUE TITLE
在暗黑主题下，没有闪烁的鼠标光标

### ISSUE THREAD

**Issue by uoow** [adonais/skylark#47]
在暗黑主题下，没有闪烁的鼠标光标
![skylark](https://user-images.githubusercontent.com/46880270/218941300-ebfacdc6-b262-43ec-a203-0f77b818d47e.png)

**Comment by adonais** [comment]
可能是配置文件污染, 先备份skylark安装目录下的conf文件夹, 然后删除conf文件夹下除conf.d目录外的所有文件.

**Comment by uoow** [comment]
> 

应该是配置文件的问题，我把整个程序的目录清空再解压使用就正常了。
