### ISSUE TITLE
更新不是太方便。

### ISSUE THREAD

**Issue by gsh456** [adonais/skylark#49]
更新不是太方便。每次都要下载压缩包后，全量替换掉。要是有exe 安装版，就好了。

**Comment by adonais** [comment]
我怎么觉得解压缩覆盖比点下一步下一步的要方便很多.
等配置文件没多大变动, 不再形成配置文件污染之后我会考虑部署自动更新.
提前说一下, 下一个版本删除了兼容旧配置的代码, 需要手动删除conf\*.conf文件再更新, 如果用户修改过conf\*.conf文件,
请先备份后再删除.
新版本最大变动是工具栏使用了矢量图标, 可任意缩放工具栏, 通过修改配置文件可增减或修改工具栏功能.

**Comment by gsh456** [comment]
> 
好吧，不过还是期待 安装版
