### ISSUE TITLE
version release feedback

### ISSUE THREAD

**Issue by xperezxin** [adonais/skylark#50]
> 目前普遍release的tag样式，只打版本号，软件下载名称就不需要打上版本号了(普遍也是打上了)，这样对于更新者只需要批量替换版本号即可获取最新下载地址  

![image](https://user-images.githubusercontent.com/31504184/221582575-81bb70d2-d58e-4822-86ef-5c048f86cbb2.png)

![image](https://user-images.githubusercontent.com/31504184/221582636-546b60b9-5e8a-4349-852b-c9048d7dde0c.png)

**Comment by adonais** [comment]
没标记版本号的放在 https://sourceforge.net/projects/libportable/files/Skylark/
