### ISSUE TITLE
Alt+F4，窗口没响应（版本：3.0.6，X64）

### ISSUE THREAD

**Issue by uoow** [adonais/skylark#52]
如题，想用alt+F4快捷键关闭窗口，发现没反应

**Comment by adonais** [comment]
https://github.com/adonais/skylark/commit/ca6a7e5624ccbcaea1d670fbf04b0cf749f11579
照这位置修改一下

**Comment by uoow** [comment]
> [ca6a7e5](https://github.com/adonais/skylark/commit/ca6a7e5624ccbcaea1d670fbf04b0cf749f11579) 照这位置修改一下

可以了。回复速度超快啊
