### ISSUE TITLE
几个小问题，复制粘贴，搜索，关机保存

### ISSUE THREAD

**Issue by jms4000** [adonais/skylark#54]
经过作者的努力，软件越来越完善了，现在是常开常驻软件；

使用中几个小问题反馈一下，有此问题是在前版本，后面没试：
1。碰到过几次，复制一段文字搜索不到，在另外的软件可以搜到，后来发现是里面藏了一个回车/换行符，所以可能搜索的文字没有自动去除两边的空白符；3.0.4
2。碰到过几次，在同一个文件里复制文字后想粘贴，但是粘贴按钮不可用，无意中切换文件再切回原文件才可以粘贴；刚才复制这段文字想粘贴也是按钮不行，但是右键可以，切换窗口后可以；3.0.7
3。因为win10和win11经常无故导致电脑重启了，然后再打开skylark，原来打开的文件不会自动打开，特别是没有保存过的文件（经常作临时笔记用）会永远消失（如果是手动关闭软件，这些问题都不存在），以前用的那个软件就没这个问题；3.0.7

**Comment by adonais** [comment]
> 经过作者的努力，软件越来越完善了，现在是常开常驻软件；
> 
> 使用中几个小问题反馈一下，有此问题是在前版本，后面没试： 1。碰到过几次，复制一段文字搜索不到，在另外的软件可以搜到，后来发现是里面藏了一个回车/换行符，所以可能搜索的文字没有自动去除两边的空白符；3.0.4 2。碰到过几次，在同一个文件里复制文字后想粘贴，但是粘贴按钮不可用，无意中切换文件再切回原文件才可以粘贴；刚才复制这段文字想粘贴也是按钮不行，但是右键可以，切换窗口后可以；3.0.7 3。因为win10和win11经常无故导致电脑重启了，然后再打开skylark，原来打开的文件不会自动打开，特别是没有保存过的文件（经常作临时笔记用）会永远消失（如果是手动关闭软件，这些问题都不存在），以前用的那个软件就没这个问题；3.0.7

哦, 粘贴问题确实有出现的机率, 这个问题马上就能修复了.
关于电脑无故重启或断电这种情况, 以后的版本可能会有一个自动备份的可选项, 但3.x版本不会考虑, 自动备份对系统资源的消耗很大, 需要频繁写入磁盘.
