### ISSUE TITLE
现在或者以后有没有对比文件的功能？

### ISSUE THREAD

**Issue by broommonk** [adonais/skylark#55]
感觉就差这个对比功能，界面那些不是太在意的话哈，其他都很完美，特别是速度很完美。

**Comment by broommonk** [comment]
界面也没有问题，只是tab那里的样式稍微美化一下下，就很很不错，淘汰掉notepad++

**Comment by adonais** [comment]
https://github.com/adonais/skylark/issues/31

**Comment by broommonk** [comment]
内置一个简单的对比行那种就够满足 大部分需求了

**Comment by adonais** [comment]
会把它列入开发计划, 但4.x版本不会有
