### ISSUE TITLE
未保存为JSON文件时格式化JSON效果不佳

### ISSUE THREAD

**Issue by gh419** [adonais/skylark#58]
Skylark Edit v3.0.10 64bit (UNICODE)
1.粘贴一段JSON格式文本到编辑器
2.在右下角将“不支持高亮”改为“json”
3.ctrl+f6格式化，效果如图：
![image](https://user-images.githubusercontent.com/25259465/234784541-b2c962a9-4ca7-46be-8042-ad7c85ac4ce7.png)
期望的效果如图
![image](https://user-images.githubusercontent.com/25259465/234784621-bbc13a0a-b911-4a31-8706-855f1423426a.png)

**Comment by adonais** [comment]
skylark支持.clang-format或者_clang-format配置文件自定义格式.
同时也支持全局.clang-format或_clang-format配置文件, 把它放入conf文件夹就可以了.
但新文件不存在路径, 所以只能启用全局的clang-format配置文件
