### ISSUE TITLE
规则yaml文件、打开后是乱码，且更换编码后，依旧显示错误

### ISSUE THREAD

**Issue by ChenYueC** [adonais/skylark#59]
默认打开后
![image](https://user-images.githubusercontent.com/82785993/236972228-d0559e76-4ec6-46b5-8a52-cec815a0977d.png)

更换编码保存，重新打开后
![image](https://user-images.githubusercontent.com/82785993/236972312-638b1eb0-2fd6-49ba-8243-1d3aca0c8180.png)

使用notepad++正常
![image](https://user-images.githubusercontent.com/82785993/236984488-190aca4a-5a62-4b7f-82a8-793f4bd51bf4.png)

下面是源文件、已将yaml后缀更改为csv，否则无法进行上传
[clash_config.csv](https://github.com/adonais/skylark/files/11426842/clash_config.csv)

**Comment by adonais** [comment]
新版本已修复
