### ISSUE TITLE
希望对18030的支持更好一些

### ISSUE THREAD

**Issue by kli2013** [adonais/skylark#6]
现在能正常打开(编辑、保存)18030编码的文件,

只是显示的还是936简体,如果能显示为18030就好了

现在能找到的源生直接能打开18030显示的只有cnbook和wxmedit

其他大部分文本编辑软件都完全不能识别

少数打开后手动更改编码才能显示

**Comment by adonais** [comment]
只是指示器显示为cp936而已, 主要是为了保持与其他显示编码的一致性.
实际上支持完整的GB18030编码.
