### ISSUE TITLE
Please add syntax highlighting to more languages

### ISSUE THREAD

**Issue by ghost** [adonais/skylark#62]
Both editor are using Scintilla but Notepad-- out of the box has syntax highlighting for more languages than Skylark. It's very annoying when you opened a file only to realize syntax highlighting for it is not available.

**Comment by adonais** [comment]
I don't have time to add all the syntax highlighting options.
I'll add the syntaxes that are of interest to the user first.
You can specify the language,
Or you can add it yourself by modifying the lua scripts.

**Comment by iahunq** [comment]
> I don't have time to add all the syntax highlighting options. I'll add the syntaxes that are of interest to the user first. You can specify the language,

Please add Pascal.

> Or you can add it yourself by modifying the lua scripts.

How?

**Comment by adonais** [comment]
Click [#62](https://github.com/adonais/skylark/commit/4c471a20d2133b36a92f3b3c3f47adcc44d41537), 
to see the changes in the conf\script-opts\user_docs.lua and conf\script-opts\user_pascal.lua files.
