### ISSUE TITLE
触摸板滚动方向和自动保存

### ISSUE THREAD

**Issue by leesings** [adonais/skylark#63]
现在的触摸板滚动方向和水平滚动条滚动方向是一致的，期望触摸板滚动方向和水平滚动条滚动方向相反，类似手机触摸屏触摸滚动的逻辑，比较符合触摸板操作直觉

希望能有一个自动保存的选项，可以配置保存间隔和策略，防止临时写的东西意外丢失

软件现在很棒了，用的也很顺手，作者大佬加油呀！

**Comment by adonais** [comment]
自动保存会出现在下一个大版本.
操作系统不支持触摸板水平相反滚动的设置, 本身水平滚动就是极少进行的操作, 看不出有何意义.

**Comment by adonais** [comment]
自动保存会出现在下一个大版本.
操作系统不支持触摸板水平相反滚动的设置, 本身水平滚动就是极少进行的操作, 看不出有何意义.

**Comment by leesings** [comment]
我经常带着笔记本移动办公，还挺习惯使用触摸板操作的，感觉比鼠标效率高😄
我记得之前的版本好像是相反滚动方向的，现在调整了嘛

**Comment by leesings** [comment]
#1
