### ISSUE TITLE
双击关闭标签

### ISSUE THREAD

**Issue by WELL-TESLA** [adonais/skylark#64]
你好，请问您有空的时候能否增加一个双击标签关闭标签的功能？

**Comment by Bush2021** [comment]
![2023-07-03_104657](https://github.com/adonais/skylark/assets/79072750/0a87a527-52e9-415c-9ea1-162273834432)
早就有此功能了。

**Comment by WELL-TESLA** [comment]
哦哦哦是我没找到，不好意思。该说就说，这个软件是真好用
