### ISSUE TITLE
Add an option to make the UI font larger

### ISSUE THREAD

**Issue by iahunq** [adonais/skylark#67]
I have a large screen and the current UI font is too small for me. Please make the icon larger, too.

**Comment by adonais** [comment]
You should enable DPI for the OS, the editor will scale with DPI!

**Comment by iahunq** [comment]
> You should enable DPI for the OS, the editor will scale with DPI!

I already scaled my screen to 125%. The text editor area followed the setting but the rest of the UI don't. I'm running Windows 8.1 if this matters.

**Comment by adonais** [comment]
The DPI of win7/win8.x is not perfect, So skylark only supports DPI of windows 10 or later.

**Comment by iahunq** [comment]
> The DPI of win7/win8.x is not perfect, So skylark only supports DPI of windows 10 or later.

OK, I got it.
