### ISSUE TITLE
Unable to run Lua script which needs input from the user

### ISSUE THREAD

**Issue by iahung2** [adonais/skylark#69]
It seems Skylark doesn't have a virtual terminal emulator so input from the user is impossible and thus the Lua script is unable to run.

**Comment by yxl0756** [comment]
Yes, there is no interaction with the user in GUI mode, it is possible to run lua scripts in command line mode (skylark -lua xxx.lua), but I found a bug in command line mode and I will fix it

**Comment by iahung2** [comment]
> Yes, there is no interaction with the user in GUI mode, it is possible to run lua scripts in command line mode (skylark -lua xxx.lua), but I found a bug in command line mode and I will fix it

OK. I will accept Skylark's limitations. But I think if I have to use the command line, I will use Lua directly.
