### ISSUE TITLE
克隆行的功能没有吗？

### ISSUE THREAD

**Issue by yahuudang** [adonais/skylark#70]
速度反应快，但是还是相比其它编辑器，编辑的一些功能还是少了不少。很难做到替换。
我把SumatraPDF放了一个软链接，大小还是有30M，把全部插件目录去掉也还有15M。
EditPlus的体积不到7M
期望可以把编辑功能先做丰富一点，比如大纲功能我也没找到。
还有一些细节，比如清理最近打开列表，应该放在最近打开的菜单里作为子项，否则很容易误点击。

**Comment by adonais** [comment]
不带插件 7.75M, 压缩后 2.7M
![skylark-shot1](https://github.com/adonais/skylark/assets/11960628/4df4e40a-dbf2-4a7c-8c95-5f725df8652f)
以现在的硬盘来说, 大小几兆不关紧要.  有的文件看起来很小, 但运行内存占用却一点都不小.
