### ISSUE TITLE
无法正确打开快捷方所指向的目标

### ISSUE THREAD

**Issue by leoxxx** [adonais/skylark#72]
尝试拖放txt文件的快捷方式，只打开了lnk文件，并没有打开指向的目标文件。试了一下UE和NOTEPAD2没有此问题，可以正常打开指向的目标文件。

**Comment by adonais** [comment]
使用右键打开即可.
lnk本身是一个文件, 可以用16进制编辑它.

**Comment by adonais** [comment]
使用右键打开即可.
lnk本身是一个文件, 可以用16进制查看和编辑它.
