### ISSUE TITLE
当文本被其它程序修改而重新加载后不能保持在当前视图

### ISSUE THREAD

**Issue by cnker** [adonais/skylark#78]
使用版本：Skylark Editor v4.0.2 32bit (UNICODE)

编译信息：clang 15.0.7 (2023-08-14 08:23:43 UTC)

当文本被其它程序修改后，选择重新加载，不能保持在当前视图位置，而是会跳到文件尾部。

![20230820225040](https://github.com/adonais/skylark/assets/1463747/103de733-7ae4-443f-b837-96ef6b5745f3)

**Comment by adonais** [comment]
早期的版本是保持在当前视图位置, 但这样做没有意义, 因为文件可能是在头部做了修改, 保持当前位置也是个错误的位置.
反之, 保持在尾部省了一步指令, 这对加载一个频繁被修改的文件有好处.

**Comment by cnker** [comment]
emeditor、everedit，甚至是typora、VS、VS Code，在遇到其它程序修改并重新加载后，都是保持在原视图位置。

所以还是希望skylark能采用相同逻辑，“保持原视图位置”，或是能提供一个设置选项来开启这个逻辑。

**Comment by adonais** [comment]
如果文件不是频繁被第三方软件修改, 可以使用shift+f5手动重载, 它会保持光标在原先行.
