### ISSUE TITLE
普通文本时，支持json格式化，而不是json文件才支持

### ISSUE THREAD

**Issue by ZxcSoft** [adonais/skylark#8]
![image](https://user-images.githubusercontent.com/5788555/176139919-5853592f-8b99-41c3-a90c-4277ce2dd3af.png)

我拷贝的json文本，希望能当前文件json格式化。这样不用我进行保存这一步了

**Comment by adonais** [comment]
在状态栏,  点击 "不支持高亮",  在弹出菜单中选择JSON, 然后就可以格式化了.
