### ISSUE TITLE
电脑A盘没有插入，每次打开skylark 都会有这个没有磁盘的提示。禁用a盘后就不会提示了。

### ISSUE THREAD

**Issue by lj1191** [adonais/skylark#81]
![image](https://github.com/adonais/skylark/assets/32461469/98b21790-54bd-493e-b2a0-8b0d93d3ec5d)
如图。

**Comment by adonais** [comment]
没有测试环境, 所以不能肯定是否修复.

**Comment by lj1191** [comment]
插入一个空的sd读卡器，没有卡在里面就会提示。有修复的话我可以测试看看

**Comment by lj1191** [comment]
4.05版已经不会有插入错误提示，同时视图->文件管理器 看不到u盘了

**Comment by adonais** [comment]
> 4.05版已经不会有插入错误提示，同时视图->文件管理器 看不到u盘了

因为U盘也可能出现损坏的情况, 出现类似的问题, 所以补丁的意思是文件管理器只加载本地硬盘.

**Comment by lj1191** [comment]
好哈 辛苦了
