### ISSUE TITLE
有没有可能支持文档对比或多开

### ISSUE THREAD

**Issue by yaoyao5128** [adonais/skylark#9]
发现skylark不支持多开，请问怎么用skylark对比两个文档。

**Comment by adonais** [comment]
没有哪个文档比较工具比Beyond compare做得更好,npp的文档比较功能相比前者就是个垃圾,还经常导致卡死崩溃.
skylark不支持文档比较功能, 也不支持多开, 目前没有这方面的开发计划.

**Comment by jackdiy** [comment]
> 没有哪个文档比较工具比Beyond compare做得更好,npp的文档比较功能相比前者就是个垃圾,还经常导致卡死崩溃. skylark不支持文档比较功能, 也不支持多开, 目前没有这方面的开发计划.

SkyLark可否考虑标签可以拉出来变成单独窗口，不一定需要多开，因为这样方便同屏查看多个文档内容
