### ISSUE TITLE
4.0.8 暗黑主题出现白条

### ISSUE THREAD

**Issue by Bush2021** [adonais/skylark#97]
如图，系统是 Windows 11：
![2023-12-01_091522](https://github.com/adonais/skylark/assets/79072750/c576cb1d-5b50-451a-88c1-cf9df062dc81)

最大化窗口后，顶部白条消失，底部白条仍然存在：
![2023-12-01_091536](https://github.com/adonais/skylark/assets/79072750/85b1db38-ba1e-4418-ac17-76ef7006e5c3)

**Comment by 7peanuts** [comment]
我也出现这个白条了

**Comment by adonais** [comment]
我测试了一下, 在自定义了工具栏图标大小后会出现此情况.
附件解压, 覆盖原文件, 看是否修复?
[Uploading skylark_x64-hotfix.zip…]()

**Comment by Bush2021** [comment]
> 我测试了一下, 在自定义了工具栏图标大小后会出现此情况. 附件解压, 覆盖原文件, 看是否修复? [skylark_x64-hotfix.zip](https://github.com/adonais/skylark/files/13538065/skylark_x64-hotfix.zip)

上面的白条没有了，下面那个还在，而且只有在全屏状态下存在，缩小的时候不会有。

我也是默认设置，而且我翻新了 Skylark 重新调整为暗黑主题也能复现这个。

**Comment by adonais** [comment]
> > 
> 上面的白条没有了，下面那个还在，而且只有在全屏状态下存在，缩小的时候不会有。
> 
> 我也是默认设置，而且我翻新了 Skylark 重新调整为暗黑主题也能复现这个。
不知道是不是显示器的问题, 下面的白线我这里不显示出来, 但某些时候状态栏确实被覆盖了1px.
试试这个新编译的版本.
[skylark_x64-hotfix2.zip](https://github.com/adonais/skylark/files/13545963/skylark_x64-hotfix2.zip)
